
ALTER TABLE RECETTE
DROP CONSTRAINT fk1_recette
DROP CONSTRAINT fk2_recette;

ALTER TABLE INGREDIENT_CATEGORIE
DROP CONSTRAINT fk1_ingredient_categorie
DROP CONSTRAINT fk2_ingredient_categorie;

ALTER TABLE ETAPE
DROP CONSTRAINT fk1_etape;

--ALTER TABLE INGREDIENT
--DROP CONSTRAINT fk_ingredient;

ALTER TABLE INGREDIENT_REMPLACEMENT
DROP CONSTRAINT PK_ingredient_remplacement
DROP CONSTRAINT fk1_ingredient_remplacement
DROP CONSTRAINT fk2_ingredient_remplacement;

ALTER TABLE  INGREDIENT_REGIME
DROP CONSTRAINT pk_ingredient_regime
DROP CONSTRAINT fk1_ingredient_regime
DROP CONSTRAINT fk2_ingredient_regime;

ALTER TABLE ILLUSTRATION
DROP CONSTRAINT FK_illustration;

ALTER TABLE INGREDIENTS
DROP CONSTRAINT fk1_ingredients
DROP CONSTRAINT fk2_ingredients;

ALTER TABLE PLANNING
DROP CONSTRAINT fk1_planning
DROP CONSTRAINT fk2_planning;

ALTER TABLE UTILISATEUR_DISPOSE
DROP CONSTRAINT fk1_utilisateur_dispose
DROP CONSTRAINT fk2_utilisateur_dispose;

ALTER TABLE LISTE_D_ACHATS
DROP CONSTRAINT fk1_liste_d_achats
DROP CONSTRAINT fk2_liste_d_achats;

ALTER TABLE ARCHIVE_LISTE
DROP CONSTRAINT fk1_archive_liste
DROP CONSTRAINT fk2_archive_liste;

ALTER TABLE ARCHIVE_PLANNING
DROP CONSTRAINT fk1_archive_planning
DROP CONSTRAINT fk2_archive_planning;


DROP TABLE ARCHIVE_LISTE;
DROP TABLE ARCHIVE_PLANNING;
DROP TABLE LISTE_D_ACHATS;
DROP TABLE UTILISATEUR_DISPOSE;
DROP TABLE INGREDIENTS;
DROP TABLE PLANNING;
DROP TABLE INGREDIENT_REMPLACEMENT;
DROP TABLE INGREDIENT_REGIME;
DROP TABLE UTILISATEUR;
DROP TABLE ETAPE;
DROP TABLE RECETTE;
DROP TABLE CATEGORIE;
DROP TABLE REGIME;
DROP TABLE ILLUSTRATION;
DROP TABLE INGREDIENT;
DROP TABLE INGREDIENT_CATEGORIE;


